# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: nice-beer github action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: cd packages/nice-beer/
    - run: yarn
    - run: yarn build --if-present
    - run: yarn test --if-present
      env:
        CI: true
    - run: cd ../nice-drink/
    - run: yarn
    - run: yarn build --if-present
    - run: yarn test --if-present
      env:
        CI: true
